name: Vuepress Publish

on: [push]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & Deploy
        uses: JamesIves/github-pages-deploy-action@3.0.4
        with:
          ACCESS_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          BRANCH: gh-pages
          FOLDER: .vuepress/dist
          BUILD_SCRIPT: npm install && npm run build
